version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - backend-network

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
